name: PyPhysX install in conda
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
      - uses: actions/checkout@v2
      - run: |
          pip install .
