name: PyPhysX
on: [ push ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.8' ] # , '3.9'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: System Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install freeglut3-dev
        if: runner.os == 'Linux'

#      - name: Build without tests
#        run: |
#          pip3 install .
#          pip3 install pytest
#        if: runner.os != 'Linux'

      - name: Install
        run: |
          pip3 install .
#        if: runner.os == 'Linux'
      - name: Test
        run: |
          pip3 install pytest
          pytest tests
#        if: runner.os == 'Linux'
